### ISSUE TITLE
Cannot read property 'major' of null

### ISSUE THREAD

**Issue by cloudlena** [davidmarkclements/install-nw#2]
I installed the package globally and then tried to execute "install-nw" from the terminal. The readme states, that it should automatically use the latest version if I don't state a version with the command. That didn't work for me since I got an error instead:

```
/usr/local/lib/node_modules/install-nw/cmd.js:119
  version = [v.major, v.minor, v.patch].join('.');
              ^
TypeError: Cannot read property 'major' of null
    at down (/usr/local/lib/node_modules/install-nw/cmd.js:119:15)
    at init (/usr/local/lib/node_modules/install-nw/cmd.js:70:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/install-nw/cmd.js:39:10)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

When I then used the same command with a version, it worked.

**Comment by davidmarkclements** [comment]
thanks for reporting this, appreciated and sorted
